name: tests

on: [pull_request, push]

jobs:
  test:
    strategy:
      matrix:
        node: [16, 18, 20]
        tz: [UTC, America/New_York, America/Los_Angeles, America/Phoenix, Asia/Hong_Kong]
    
    name: Node ${{ matrix.node }}, ${{ matrix.tz }} timezone

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node}}
      - uses: actions/checkout@v3
      - name: set timezone
        run: sudo timedatectl set-timezone ${{ matrix.tz }}
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: test
        run: npm test
      
